config/routes.rb
Rails.application.routes.draw do
 
  
  post '/rate' => 'rater#create', :as => 'rate'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'category#index'

  patch 'ads/edit', to: 'ads#edit'
    resources :category
    resources :ads
    devise_for :users

end

app/models/ad.rb
class Ad < ApplicationRecord
  validates_presence_of :category_id, :user_id, :title, :description
  
  belongs_to :user
  belongs_to :category

  def number_to_currency_br(number)
    number_to_currency(number, :unit => "R$ ", :separator => ",", :delimiter => ".")
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates_presence_of :name, :user_id
  
  has_many :ads
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :ads
  has_many :categories

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController

  def index
    @ads = Ad.all
  end

  def new 
    @ad = Ad.new

  end

  def create
    @user = current_user
    @ad = @user.ads.new(params_ad)

    if @ad.save!
      redirect_to category_path(@ad.category.id), notice: "Ads creating sussefully!"
    else
      render :new
    end
  end
  
  def edit
    @ad = Ad.find(params[:id])
  end

  def update
    @ad = Ad.find(params[:id])
    if @ad.update(params_ad)
      redirect_to category_path(@ad.category.id), notice: "Ads updating sussefully!"
    else
      render :edit
    end
  end

  def show
    @ad = Ad.find(params[:id])
    if @ad.user.id == current_user.id
     @ad
    else
      render :index, notice: "Deu ruim"
    end
  end

  def destroy
    @ads = Ad.find(params[:id])
    category = @ads.category
    @ads.destroy
    redirect_to category_path(category.id)
  end

  private

  def params_ad
    params.require(:ad).permit(:id, :title, :category_id, :price, :description)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/category_controller.rb
class CategoryController < ApplicationController
  before_action :authenticate_user!

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @user = current_user
    @category = @user.categories.new(params_category)
    
    if @category.save!
      redirect_to category_index_path
    else
      render :new
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
      if @category.update params_category
        redirect_to category_index_path
      else
        render 'edit'
      end
  end

  def show
    @category = Category.find(params[:id])
    if @category.user_id == current_user.id
     @category
    else
      render :index, notice: "Deu ruim"
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to category_index_path
  end


  private

  def params_category
    params.require(:category).permit(:name, :id)
  end

end

app/helpers/ads_helper.rb
module AdsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/views/ads/edit.html.erb
<div class="container">
  <div class="row">
    <%= form_for @ad, :url=> {:action => "update"} do |f| %>
      <div class="form-group boots">
        <%= f.label :title %><br>
          <%= f.text_field :title, placeholder: "Edit your Ad" , class: "form-control" , id: "exampleFormControlInput1"
            %>
            <br>
            <div class="form-group boots">
        <%= f.label :price %>
          <%=f.text_field :price, class: "form-control" , id:"exampleFormControlInput1" %>
      </div>
      </div>
      <div class="form-group boots">
        <%= f.label :description %><br>
          <%= f.text_area :description, placeholder: "Updating your Ads" ,class:"form-control",
            id:"exampleFormControlSelect1" %><br>
      </div>
      <%= f.submit "Edit" %>
        <% end %>
          <%= link_to 'Back' , ad_path(@ad.id) %>
  </div>
</div>

app/views/ads/new.html.erb
<div class="container">
  <div class="row">
    <%= form_for @ad, :url=> {:action => "create"} do |f| %>
      <div class="form-group boots ">
        <%= f.label :title %><br>
          <%= f.text_field :title, placeholder: "Create your Ad" ,class: "form-control" ,
            id:"exampleFormControlInput1"%>
      </div>
      <div class="form-group boots">
        <%= f.label :price %>
          <%=f.text_field :price, class: "form-control" , id:"exampleFormControlInput1" %>
      </div>
      <div class="form-group boots">
        <%= f.label :description %><br>
          <%= f.text_area :description, placeholder: "Create your Ad" ,class: "form-control" ,
            id:"exampleFormControlInput1" %><br>
            <%= f.hidden_field(:category_id, value: params["category_id"]) %>

      </div>
      <%= f.submit "Create" %>

        <% end %>
          <%= link_to 'Home' , ads_path %>
  </div>
</div>

app/views/ads/show.html.erb
<div class="container">
  <div class="row">
    <table class="table table-hover table-dark">
      <thead>
        <tr>
          <th scope="col">
            <%= current_user.email %>
          </th>
          <th scope="col"></th>
          <th scope="col"></th>
          <th scope="col"></th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th scope="row">
            <%= @ad.user.email %>
          </th>
          <td>
            <%= @ad.title %>
          </td>
          <td>
            <%= @ad.price %><br>
          </td>
          <td>
            <%= @ad.description %><br>
          </td>
          <td>
            <%= @ad.category.name %>
          </td>

        </tr>

        <th scope="row">
          <%= link_to 'Edit' , edit_ad_path(@ad.id) %>
        </th>
        <td colspan="2"></td>
        <td colspan="2"></td>
        </tr>
      </tbody>
    </table>
    <%= link_to 'Home' , category_index_path %>
  </div>
</div>

app/views/category/edit.html.erb
<div class="container">
   
      <%= form_for @category do |f| %>
        <div class="form-group">

        </div>
        <div class="form-group boots">
          <%= f.label :Edit %>
            </label>

        </div>
        <div class="form-group">
          <label for="exampleFormControlSelect2">
            <%= f.text_field :name, placeholder: "Edit your Category" %>
          </label>
        </div>

        <%= f.submit%>
          <% end %>
    
    <%= link_to 'Home' , category_index_path %>
      <%= link_to 'Logout' , destroy_user_session_path, method: :delete %>

  </div>
</div>

app/views/category/index.html.erb
<table class="table table-striped table-dark">
	<thead>
		<tr>
			<th scope="col">
				<%= link_to 'New' , new_category_path %><br>
			</th>
			<th scope="col">

			</th>
			<th scope="col"></th>
			<th scope="col">
				<%= link_to 'Logout' , destroy_user_session_path, method: :delete %>
			</th>
		</tr>
	</thead>
	<tbody>
		<% @categories.each do |category| %>
			<tr>
				<th scope="row">
					<%= category.name %>
				<td>
					<%= link_to 'Edit' , edit_category_path(category.id) %>
				</td>
				<td>
					<%= link_to 'Delete' , category_path(category), method: :delete %>
				</td>
				<td>
					<%= link_to 'Show' , category_path(category.id) %><br>
				</td>
			</tr>
			<% end %>
	</tbody>
</table>

app/views/category/new.html.erb
<div class="container">
  <div class="row">

    <table class="table table-striped table-dark">
      <thead>
        <tr>
          <th scope="col"></th>
          <th scope="col">
            <%= link_to 'Home' , category_index_path %>
          </th>
          <th scope="col"></th>
          <th scope="col">
            <%= link_to 'Logout' , destroy_user_session_path, method: :delete %>
          </th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th scope="row"></th>
          <td>
            <%= form_for @category, :url=> {:action => "create"} do |f| %>
              <%= f.label :category %>
                <%= f.text_field :name, placeholder: "Create your Category" %>
                  <%= f.submit "Create" %>
                    <% end %>
          </td>

        </tr>
      </tbody>
    </table>
  </div>
</div>

app/views/category/show.html.erb
<table class="table table-hover table-dark">
  <thead>
    <tr>
      <th scope="col">
        <%= @category.name %><br>
      </th>
      <th scope="col"></th>
      <th scope="col">
        <%= @category.user.email %><br>
      </th>
      <th scope="col">
        <%= link_to 'Logout' , destroy_user_session_path, method: :delete %>
      </th>
    </tr>
  </thead>
  <tbody>
    <% if @category.ads.present? %>
      <% @category.ads.each do |ad|%>
        <tr>
          <th scope="row">
            <%= ad.title%>
          </th>
          <td>
            <%= link_to 'Edit AD' , edit_ad_path(ad.id) %>
          </td>
          <td>
            <%= link_to 'Delete AD' , ad_path(ad), method: :delete %>
          </td>
          <td>
            <%= link_to 'Show AD' , ad_path(ad.id) %>
          </td>
        </tr>
        <% end %>
          <% end %>
  </tbody>
  <table class="table table-hover table-dark">
    <thead>
      <tr>
        <th scope="col"> </th>
        <th scope="col"> </th>
        <th scope="col">
          <%= link_to 'Edit Category' , edit_category_path(@category.id) %>
        </th>
        <th scope="col">
          <%= link_to 'New AD' , new_ad_path(category_id: @category.id) %><br>
        </th>
      </tr>
    </thead>
  </table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ConstructShopping</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>